channels:
  - conda-forge
  - pytorch
  - nvidia
  - bioconda
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - ipython
  - ipykernel
  - ipywidgets
  - jaxlib>=0.4.26
  - matplotlib
  - numpy
  - pandas
  - pip
  - scvi-tools
  - scanpy
  - python-igraph
  - scikit-misc
  - leidenalg
  - fastp
  - pixelator

